### ISSUE TITLE
May Launch Checklist Items

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/builders#12]
Launch Checklist
- [x] Update share image (open graph) - logo-builders (edited) 
- [x] Confirm favicon
- [x] Redir asdfadsdfl folder > real page
- [x] Overall: Make sure all links are correct
- [x] Meta: Remove NoFollow/SEO Tag
- [x] Add GA Tag
